"""Core loading and normalization utilities for Canopy explorations."""

from .dxpx import DXPXLoadError, DXPXRun, load_dxpx, load_dxpx_laps
from .config import (
	AnalysisConfig,
	BaselineConfig,
	DatasetConfig,
	ExportConfig,
	FilterConfig,
	PlotConfig,
	SweepVariableConfig,
)
from .analysis import (
	MetricResult,
	analyze_metric,
	analyze_runs,
	build_filter_mask,
	reduce_signal,
)
from .exploration import (
	ExplorationDefinition,
	JobRecord,
	SweepVariable,
	discover_job_variables,
	load_job_records,
	load_exploration_definition,
)
from .metric import Metric, average_metric, default_metrics, evaluate_metric, source_metric
from .plot_data import (
	FacetedHeatmapData,
	HeatmapPlotData,
	LinePlotData,
	ParallelCoordinatesData,
	build_faceted_heatmap_data,
	build_heatmap_data,
	build_line_data,
	build_parallel_coordinates_data,
	build_plot_data,
)
from .plotting import (
	render_faceted_heatmap,
	render_heatmap,
	render_line,
	render_parallel_coordinates,
	render_plot_data,
)
from .results import (
	AnalysisRow,
	BaselineResult,
	ComparedRow,
	GridPoint,
	GridResult,
	analyze_baseline,
	build_grid,
	compare_rows_to_baseline,
	compute_delta,
	find_missing_runs,
	join_sweep_variables,
	resolve_baseline_laps,
	run_index,
)
from .turn_zones import TurnZoneError, add_turn_zones

__all__ = [
	"DXPXLoadError",
	"DXPXRun",
	"AnalysisConfig",
	"AnalysisRow",
	"BaselineResult",
	"ComparedRow",
	"GridPoint",
	"GridResult",
	"MetricResult",
	"BaselineConfig",
	"DatasetConfig",
	"ExportConfig",
	"FilterConfig",
	"FacetedHeatmapData",
	"HeatmapPlotData",
	"ExplorationDefinition",
	"JobRecord",
	"Metric",
	"LinePlotData",
	"PlotConfig",
	"ParallelCoordinatesData",
	"SweepVariable",
	"SweepVariableConfig",
	"TurnZoneError",
	"add_turn_zones",
	"analyze_baseline",
	"analyze_metric",
	"analyze_runs",
	"average_metric",
	"default_metrics",
	"build_faceted_heatmap_data",
	"build_heatmap_data",
	"build_line_data",
	"build_parallel_coordinates_data",
	"build_plot_data",
	"render_faceted_heatmap",
	"render_heatmap",
	"render_line",
	"render_parallel_coordinates",
	"render_plot_data",
	"build_filter_mask",
	"build_grid",
	"compare_rows_to_baseline",
	"compute_delta",
	"discover_job_variables",
	"evaluate_metric",
	"find_missing_runs",
	"join_sweep_variables",
	"load_job_records",
	"load_exploration_definition",
	"load_dxpx",
	"load_dxpx_laps",
	"reduce_signal",
	"resolve_baseline_laps",
	"run_index",
	"source_metric",
]